name: Build, Test and Deploy Lazybones CI

on: [push]

jobs:
  build-plugin:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lazybones-gradle-plugin

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache Maven Caches
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-caches-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: ${{ runner.os }}-maven-caches

      - name: Cache Gradle Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-caches

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build and Install Locally the Plugin
        run: ./gradlew -s clean check publishToMavenLocal


  build-templates-and-app:

    runs-on: ubuntu-latest
    needs: build-plugin

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache Maven Caches
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-caches-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: ${{ runner.os }}-maven-caches

      - name: Cache Gradle Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-caches

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Package the App and Templates
        run: ./gradlew -s clean check distZip

      - name: Cache the Templates
        uses: actions/cache@v2
        with:
          path: ~/.lazybones/templates
          key: ${{ runner.os }}-lazybones-templates-${{ github.sha }}
